### ISSUE TITLE
Protocol

### ISSUE THREAD

**Issue by Tuvqlu** [iRainDropp/CPS#10]
Great Plugin! Protocol support for recent update? Ty

**Comment by Karm4lTK** [comment]
easy man, change protocol to 503

**Comment by iRainDropp** [comment]
You can do it yourself by editing the plugin.umm to support the newest
protocol or you can wait a little bit and I’ll upload a new version to
GitHub. I still have another small bug that needs to be fixed as well so
I’ll get that done and then release it.

**Comment by iRainDropp** [comment]
By editing the plugin.yml***

**Comment by iRainDropp** [comment]
Protocol has been updated.
