### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by PSYCHO1512** [iRainDropp/CPS#11]
Fatal error: Could not check compatibility between iRainDrop\CPS\Commands\CPSCommand::getOwningPlugin(): iRainDrop\CPS\Commands\Plugin and pocketmine\plugin\PluginOwned::getOwningPlugin(): pocketmine\plugin\Plugin, because class iRainDrop\CPS\Commands\Plugin is not available in phar:///home/container/plugins/CPS (2).phar/src/iRainDrop/CPS/Commands/CPSCommand.php on line 18

**Comment by iRainDropp** [comment]
What did you do right before this error happened?

**Comment by Ezinox** [comment]
I have the same error and we just restart the server and it crashes

**Comment by PSYCHO1512** [comment]
> 

i just install and start the server

**Comment by PSYCHO1512** [comment]
> What did you do right before this error happened?

**Comment by iRainDropp** [comment]
It should be fixed in the latest release, sorry for the wait.

**Comment by PSYCHO1512** [comment]
> It should be fixed in the latest release, sorry for the wait.

np
