### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by YT-Duckyyy** [iRainDropp/CPS#12]
Fatal error: Could not check compatibility between iRainDrop\CPS\Commands\CPSCommand::getOwningPlugin(): iRainDrop\CPS\Commands\Plugin and pocketmine\plugin\PluginOwned::getOwningPlugin(): pocketmine\plugin\Plugin, because class iRainDrop\CPS\Commands\Plugin is not available in phar:///home/container/plugins/CPS.phar/src/iRainDrop/CPS/Commands/CPSCommand.php on line 18

I'm using 2.0 and the latest pmmp versions

**Comment by iRainDropp** [comment]
It has been fixed in the latest release
