### ISSUE TITLE
[FR] Add activate at startup or not (config.yml)

### ISSUE THREAD

**Issue by UnEnanoMas** [iRainDropp/CPS#2]
Maybe some players do not want to have it activated, I was wondering if perhaps an option could be added so that when you enter the server, it will not be activated

for example:

#Load to start "CPS"
enable: true

**Comment by iRainDropp** [comment]
Are you asking for me to add a togglable option that enables or disables the popup for all players when they join?

**Comment by UnEnanoMas** [comment]
Yes if u can

**Comment by iRainDropp** [comment]
I added this feature for you. Let me know if you have any more suggestions / issues.
