### ISSUE TITLE
[FR] Discord Webhook

### ISSUE THREAD

**Issue by PackBundle** [iRainDropp/CPS#3]
Great plugin! Looks nice!

One request I have is maybe adding a webhook system for Discord, to send alerts on Discord as well, just incase staff are not online at the time!

**Comment by ghost** [comment]
Just use DiscordWebhookAPI from CortexPE and do it yourself.

**Comment by iRainDropp** [comment]
I know nothing about Discord Webhooks but I will look into how to implement DiscordWebhookAPI into the plugin. You can expect an update in a day - a week.

**Comment by iRainDropp** [comment]
I just finished with adding this feature. Thank you for the suggestion, if you have anymore, feel free to open another Feature Request.
